core/env.zsh
core/autocompile.zsh
core/completion.zsh
core/keymap.zsh
core/setopt.zsh

core/prompt.zsh

core/history.zsh
core/misc.zsh
core/alias.zsh

extra/git.zsh
extra/go.zsh
extra/kitty_and_ime.zsh
extra/pkgconfig.zsh
extra/nvim.zsh
extra/direnv.zsh
extra/mise.zsh
extra/python.zsh

utils/sudo.zsh
utils/tmux.zsh
utils/less.zsh
utils/prompt.zsh

utils/dotfiles.zsh
utils/expandpath.zsh
