export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
typeset -TU PATH path && path+=($HOME/.local/bin)
typeset -TU XDG_DATA_DIRS data_dirs \
  && data_dirs+=($XDG_DATA_HOME) \
  && data_dirs+=(/usr/share)
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
[[ $OSTYPE == darwin* ]] && _nvim_os=macos || _nvim_os=linux
path=($HOME/.local/nvim-$_nvim_os-*/bin(N) $path)
unset _nvim_os
